### PR TITLE
Various small fixes that needed doing.

### LINKED ISSUE #96: small issues
Hi

Image fit:
It should be adjusted to fit as the default choice when the resolution is below 660. Both for registered and anonymous user because the current view from a mobile device without logging in makes you have to click to get the adjustment and as a user it forces the fit option as default.

Email blacklist:
The issue is when you change an email, it seems like when you do that it won't do the validation to see if that email is in the blacklist or not.

Forum categories:
The problem is that when deleting a category you'll get: undefined method `id'....

Help:
It seems to crash when including a related entry. Also from the show view, the edit wiki option seems like its pointing to the wrong place (For example when trying to edit the wiki entry with id 23 related to the help entry 2, it would instead try to edit the wiki entry with id 2 when it should point to the entry with id 23).

### PR DESCRIPTION
**Pull request by kiranoot**
Close #96

### CODE REVIEW

File: app/controllers/wiki_pages_controller.rb [hunk 1]
```diff
@@ -10,7 +10,15 @@ def new
   end
 
   def edit
-    @wiki_page = WikiPage.find(params[:id])
+    if params[:id] =~ /\A\d+\Z/
```
Comment (liamwhite) [inline app/controllers/wiki_pages_controller.rb:13]: Use `\z` here. https://ruby-doc.org/core-2.6.3/Regexp.html#class-Regexp-label-Anchors
